<#
.SYNOPSIS
  Windows Task Scheduler fallback for looks-busy-agent (CLI coding agents).

.DESCRIPTION
  Mirrors scripts/schedule_launchd.sh. Registers a per-user daily task that
  (1) pre-collects read-only snapshots (email via collect_email.py, Feishu
  agenda via lark-cli --as user) into %LOCALAPPDATA%\looks-busy-agent\raw\<date>\
  and (2) runs the agent headless with a minimal tool whitelist to write the
  report. Both "Wake the computer to run this task" (WakeToRun) and "Run task
  as soon as possible after a scheduled start is missed" (StartWhenAvailable)
  are enabled — a laptop asleep at 21:00 needs both.

  Credentials: store the mailbox app-password with
    cmdkey /generic:looks-busy-agent-email /user:<mailbox> /pass
  collect_email.py reads it back through the Credential Manager API.

  NOTE: the Claude Code --allowedTools path rule on Windows has not been
  verified on a real machine yet; run `render` and `run-once` first.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File schedule_windows.ps1 install -Time 21:00 -Agent claude
  powershell -ExecutionPolicy Bypass -File schedule_windows.ps1 run-once
  powershell -ExecutionPolicy Bypass -File schedule_windows.ps1 render | status | uninstall
#>
param(
  [Parameter(Position = 0)][ValidateSet('install', 'run-once', 'render', 'status', 'uninstall')][string]$Command = 'status',
  [string]$Time = '',
  [ValidateSet('claude', 'codex', '')][string]$Agent = ''
)
$ErrorActionPreference = 'Stop'

$TaskName = 'looks-busy-agent-daily'
$DataDir = Join-Path $env:LOCALAPPDATA 'looks-busy-agent'
$ConfigPath = Join-Path $env:USERPROFILE '.config\looks-busy-agent\config.json'
$Wrapper = Join-Path $DataDir 'run_daily.ps1'
$SkillDir = Split-Path -Parent $PSScriptRoot
$Prompt = '使用 looks-busy-agent 的 run 模式，读取 ~/.config/looks-busy-agent/config.json，生成今天的工作日报，并保存到 config 的 report.output_dir 目录（文件名 <日期>.md，Markdown）。当日原始数据已预采集到 %LOCALAPPDATA%\looks-busy-agent\raw\<日期>\（email.json、calendar.json；文件缺失即该来源本次失败，按降级处理并在日报末尾 meta 行注明）。这是无人值守运行：只读取快照、按 report-policy 生成草稿并落盘、执行已授权的幂等日历写入；不做新的授权、不对外发送、不询问用户。'

function Get-ConfigValue([string]$Key, [string]$Default) {
  if (-not (Test-Path $ConfigPath)) { return $Default }
  try {
    $node = Get-Content $ConfigPath -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($part in $Key.Split('.')) { $node = $node.$part }
    if ($null -eq $node) { return $Default }
    return [string]$node
  } catch { return $Default }
}

function Resolve-Agent {
  if ($Agent) { return $Agent }
  if (Get-Command claude -ErrorAction SilentlyContinue) { return 'claude' }
  if (Get-Command codex -ErrorAction SilentlyContinue) { return 'codex' }
  return 'claude'
}

function Write-Wrapper([string]$UseAgent) {
  New-Item -ItemType Directory -Force -Path (Join-Path $DataDir 'logs'), (Join-Path $DataDir 'reports') | Out-Null
  $dataPosix = $DataDir -replace '\\', '/'
  $collect = Join-Path $SkillDir 'scripts\collect_email.py'
  $body = @"
# generated by schedule_windows.ps1 — do not edit (re-run install to regenerate)
`$ErrorActionPreference = 'Continue'
`$Log = '$DataDir\logs\run.log'
`$Out = '$DataDir\logs\last_run.json'
`$Day = Get-Date -Format 'yyyy-MM-dd'
`$Wd = @('周日','周一','周二','周三','周四','周五','周六')[[int](Get-Date).DayOfWeek]
`$off = [System.TimeZoneInfo]::Local.GetUtcOffset((Get-Date))
`$TzOff = ('{0}{1:00}:{2:00}' -f (@('+','-')[[int](`$off.TotalMinutes -lt 0)]), [math]::Abs(`$off.Hours), [math]::Abs(`$off.Minutes))
`$Raw = Join-Path '$DataDir\raw' `$Day
New-Item -ItemType Directory -Force -Path `$Raw | Out-Null
Add-Content `$Log "==== `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') looks-busy-agent start ===="
`$cfg = Get-Content '$ConfigPath' -Raw -Encoding UTF8 | ConvertFrom-Json

# --- deterministic read-only pre-collection (failures degrade, never abort) ---
if (`$cfg.sources.email.enabled) {
  python "$collect" --config "$ConfigPath" --date `$Day --output (Join-Path `$Raw 'email.json') 2>&1 | Add-Content `$Log
  if (`$LASTEXITCODE -ne 0) { Add-Content `$Log '[warn] email collection failed' }
}
if (`$cfg.sources.feishu.enabled) {
  `$cal = Join-Path `$Raw 'calendar.json'
  lark-cli calendar +agenda --as user --format json --start "`${Day}T00:00:00`$TzOff" --end "`${Day}T23:59:59`$TzOff" 2>>`$Log | Set-Content `$cal -Encoding UTF8
  `$ok = `$false
  try { `$ok = [bool](Get-Content `$cal -Raw | ConvertFrom-Json).ok } catch {}
  if (-not `$ok) { Remove-Item `$cal -ErrorAction SilentlyContinue; Add-Content `$Log '[warn] calendar collection failed' }
}

"@
  if ($UseAgent -eq 'claude') {
    $body += @"
`$job = Start-Process -FilePath 'claude' -PassThru -NoNewWindow -RedirectStandardOutput `$Out -RedirectStandardError (Join-Path '$DataDir\logs' 'claude.err.log') -ArgumentList @(
  '-p', ('今天是 ' + `$Day + '（' + `$Wd + '）。' + '$Prompt'),
  '--permission-mode', 'dontAsk',
  '--allowedTools', 'Skill,Read,Glob,Grep,Bash(date:*),Bash(lark-cli calendar:*),Edit($dataPosix/**)',
  '--output-format', 'json')
if (-not `$job.WaitForExit(1800000)) { `$job.Kill(); Add-Content `$Log '[watchdog] killed after 30min' }
`$code = `$job.ExitCode
`$result = ''
try { `$result = (Get-Content `$Out -Raw | ConvertFrom-Json).result } catch {}
if (`$code -ne 0 -or -not `$result) { Add-Content `$Log "[error] exit=`$code result_empty=`$([string]::IsNullOrEmpty(`$result))" } else { Add-Content `$Log '[ok] exit=0' }
"@
  } else {
    $body += @"
`$job = Start-Process -FilePath 'codex' -PassThru -NoNewWindow -RedirectStandardOutput (Join-Path '$DataDir\logs' 'codex.out.log') -ArgumentList @('exec', ('今天是 ' + `$Day + '（' + `$Wd + '）。' + '$Prompt'))
if (-not `$job.WaitForExit(1800000)) { `$job.Kill(); Add-Content `$Log '[watchdog] killed after 30min' }
`$code = `$job.ExitCode
"@
  }
  $body += @"
Add-Content `$Log "==== `$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') looks-busy-agent done (exit `$code) ===="
exit `$code
"@
  Set-Content -Path $Wrapper -Value $body -Encoding UTF8
}

$UseAgent = Resolve-Agent
if (-not $Time) { $Time = Get-ConfigValue 'run_time' '21:00' }

switch ($Command) {
  'install' {
    if (-not (Test-Path $ConfigPath)) { throw "config not found: $ConfigPath (run setup first)" }
    if ($Time -notmatch '^([01][0-9]|2[0-3]):[0-5][0-9]$') { throw "invalid -Time: $Time (HH:MM)" }
    if (-not (Get-Command $UseAgent -ErrorAction SilentlyContinue)) { throw "$UseAgent CLI not found in PATH" }
    Write-Wrapper $UseAgent
    $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$Wrapper`""
    $trigger = New-ScheduledTaskTrigger -Daily -At $Time
    $settings = New-ScheduledTaskSettingsSet -WakeToRun -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 40) -MultipleInstances IgnoreNew
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Description '看起来很忙 Agent 每日日报' -Force | Out-Null
    Write-Output "installed: $TaskName — daily at $Time via $UseAgent"
    Write-Output "wrapper: $Wrapper"
    Write-Output "config.schedule suggestion: {`"provider`": `"schtasks`", `"agent`": `"$UseAgent`", `"job_id`": `"$TaskName`"}"
    Write-Output 'note: 已启用「唤醒运行」+「错过后尽快运行」；笔记本需在 BIOS 允许定时唤醒才能从睡眠中启动。'
  }
  'run-once' {
    if (-not (Test-Path $ConfigPath)) { throw "config not found: $ConfigPath (run setup first)" }
    Write-Wrapper $UseAgent
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Wrapper
    exit $LASTEXITCODE
  }
  'render' {
    Write-Wrapper $UseAgent
    Write-Output $Wrapper
  }
  'status' {
    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($null -eq $task) { Write-Output 'not installed'; break }
    $info = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Output "task: $TaskName  state: $($task.State)  next: $($info.NextRunTime)  last: $($info.LastRunTime) ($($info.LastTaskResult))"
    $log = Join-Path $DataDir 'logs\run.log'
    if (Test-Path $log) { Write-Output 'last log lines:'; Get-Content $log -Tail 3 }
  }
  'uninstall' {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Output "uninstalled: $TaskName"
  }
}
