#!/usr/bin/env bash
# macOS launchd scheduler for looks-busy-agent (works with any CLI coding agent).
#
# Why this exists: cloud routines cannot read the local mailbox, Keychain or
# lark-cli. This installs a per-user launchd job that, at run_time, (1) collects
# read-only snapshots deterministically (email + Feishu agenda -> raw/<date>/),
# then (2) runs the agent headless with a minimal tool whitelist to write the
# report into report.output_dir. It never asks for new permissions or sends
# anything externally.
#
# Verified whitelist gotchas (Claude Code): file writes are governed by
# Edit(...) rules — Write(path) does not match — and absolute paths need a
# double slash: Edit(//Users/you/...).
#
# Usage:
#   schedule_launchd.sh install [--time HH:MM] [--agent claude|codex]
#   schedule_launchd.sh run-once [--agent claude|codex]
#   schedule_launchd.sh status | uninstall | render
set -euo pipefail

LABEL="com.looks-busy-agent.daily"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
DATA_DIR="$HOME/.local/share/looks-busy-agent"
CONFIG="$HOME/.config/looks-busy-agent/config.json"
WRAPPER="$DATA_DIR/run_daily.sh"
SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROMPT="使用 looks-busy-agent 的 run 模式，读取 ~/.config/looks-busy-agent/config.json，生成今天的工作日报，并用 python3 $SKILL_DIR/scripts/save_report.py --date <日期> 保存到 config 的 report.output_dir（日报正文走 stdin；必须看到 saved: 输出）。当日原始数据已预采集到 ~/.local/share/looks-busy-agent/raw/<日期>/（email.json、calendar.json；文件缺失即该来源本次失败，按降级处理并在日报末尾 meta 行注明）。这是无人值守运行：只读取快照、按 report-policy 生成草稿并落盘、执行已授权的幂等日历写入；不做新的授权、不对外发送、不询问用户。"

config_value() {
  # $1 = dotted key, $2 = default
  python3 - "$CONFIG" "$1" "$2" <<'PY' 2>/dev/null || printf '%s' "$2"
import json, sys
path, key, default = sys.argv[1:4]
try:
    node = json.load(open(path, encoding="utf-8"))
    for part in key.split("."):
        node = node[part]
    print(node if isinstance(node, str) else json.dumps(node))
except Exception:
    print(default)
PY
}

write_wrapper() {
  local agent="$1"
  mkdir -p "$DATA_DIR/logs" "$DATA_DIR/reports"
  cat > "$WRAPPER" <<EOF2
#!/bin/bash
# generated by schedule_launchd.sh — do not edit (re-run install to regenerate)
set -uo pipefail
export PATH="$PATH"
LOG="$DATA_DIR/logs/run.log"
OUT="$DATA_DIR/logs/last_run.json"
DAY="\$(date +%F)"
case "\$(date +%u)" in 1) WD=周一;; 2) WD=周二;; 3) WD=周三;; 4) WD=周四;; 5) WD=周五;; 6) WD=周六;; 7) WD=周日;; esac
TZOFF="\$(date +%z | sed 's/\\(..\\)\$/:\\1/')"
RAW="$DATA_DIR/raw/\$DAY"
mkdir -p "\$RAW"; chmod 700 "$DATA_DIR/raw" "\$RAW"
echo "==== \$(date '+%F %T') looks-busy-agent start ====" >> "\$LOG"
cd "\$HOME"

# --- deterministic read-only pre-collection (failures degrade, never abort) ---
if python3 -c "import json,sys; c=json.load(open('$CONFIG')); sys.exit(0 if c['sources']['email'].get('enabled') else 1)" 2>/dev/null; then
  python3 "$SKILL_DIR/scripts/collect_email.py" --config "$CONFIG" --date "\$DAY" \\
    --output "\$RAW/email.json" >> "\$LOG" 2>&1 || echo "[warn] email collection failed" >> "\$LOG"
fi
if python3 -c "import json,sys; c=json.load(open('$CONFIG')); sys.exit(0 if c['sources']['feishu'].get('enabled') else 1)" 2>/dev/null; then
  lark-cli calendar +agenda --as user --format json --start "\${DAY}T00:00:00\${TZOFF}" --end "\${DAY}T23:59:59\${TZOFF}" \\
    > "\$RAW/calendar.json" 2>>"\$LOG" \\
    && python3 -c "import json,sys; sys.exit(0 if json.load(open('\$RAW/calendar.json')).get('ok') else 1)" 2>/dev/null \\
    || { rm -f "\$RAW/calendar.json"; echo "[warn] calendar collection failed" >> "\$LOG"; }
fi
chmod 600 "\$RAW"/*.json 2>/dev/null

EOF2
  if [[ "$agent" == "claude" ]]; then
    cat >> "$WRAPPER" <<EOF2
claude -p "今天是 \$DAY（\$WD）。$PROMPT" \\
  --permission-mode dontAsk \\
  --allowedTools "Skill,Read,Glob,Grep,Bash(date:*),Bash(lark-cli calendar:*),Bash(python3 $SKILL_DIR/scripts/save_report.py:*),Edit(/$DATA_DIR/**)" \\
  --output-format json > "\$OUT" 2>>"\$LOG" &
pid=\$!
( sleep 1800; kill -TERM \$pid 2>/dev/null && echo "[watchdog] killed after 30min" >> "\$LOG" ) &
watchdog=\$!
wait \$pid; code=\$?
kill \$watchdog 2>/dev/null
result=\$(python3 -c "import json;print(json.load(open('\$OUT')).get('result') or '')" 2>/dev/null)
if [[ \$code -ne 0 || -z "\$result" ]]; then
  echo "[error] exit=\$code result_empty=\$([[ -z \$result ]] && echo yes || echo no)" >> "\$LOG"
else
  cost=\$(python3 -c "import json;print(json.load(open('\$OUT')).get('total_cost_usd','n/a'))" 2>/dev/null)
  echo "[ok] exit=0 cost_usd=\$cost" >> "\$LOG"
fi
echo "==== \$(date '+%F %T') looks-busy-agent done (exit \$code) ====" >> "\$LOG"
exit \$code
EOF2
  else
    cat >> "$WRAPPER" <<EOF2
codex exec "今天是 \$DAY（\$WD）。$PROMPT" >> "\$LOG" 2>&1 &
pid=\$!
( sleep 1800; kill -TERM \$pid 2>/dev/null && echo "[watchdog] killed after 30min" >> "\$LOG" ) &
watchdog=\$!
wait \$pid; code=\$?
kill \$watchdog 2>/dev/null
echo "==== \$(date '+%F %T') looks-busy-agent done (exit \$code) ====" >> "\$LOG"
exit \$code
EOF2
  fi
  chmod 700 "$WRAPPER"
}

cmd="${1:-}"; shift || true
TIME=""; AGENT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --time)  TIME="$2"; shift 2 ;;
    --agent) AGENT="$2"; shift 2 ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done
[[ -n "$TIME" ]] || TIME="$(config_value run_time 21:00)"
if [[ -z "$AGENT" ]]; then
  if command -v claude >/dev/null 2>&1; then AGENT=claude
  elif command -v codex >/dev/null 2>&1; then AGENT=codex
  else AGENT=claude; fi
fi

case "$cmd" in
  install)
    [[ -f "$CONFIG" ]] || { echo "config not found: $CONFIG (run setup first)" >&2; exit 1; }
    [[ "$TIME" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]] || { echo "invalid --time: $TIME (HH:MM)" >&2; exit 2; }
    case "$AGENT" in
      claude) command -v claude >/dev/null || { echo "claude CLI not found in PATH" >&2; exit 1; } ;;
      codex)  command -v codex  >/dev/null || { echo "codex CLI not found in PATH" >&2; exit 1; } ;;
      *) echo "unsupported --agent: $AGENT (claude|codex)" >&2; exit 2 ;;
    esac
    write_wrapper "$AGENT"
    HOUR="${TIME%:*}"; MINUTE="${TIME#*:}"
    mkdir -p "$(dirname "$PLIST")"
    cat > "$PLIST" <<EOF2
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key><array><string>/bin/bash</string><string>$WRAPPER</string></array>
  <key>StartCalendarInterval</key><dict>
    <key>Hour</key><integer>$((10#$HOUR))</integer>
    <key>Minute</key><integer>$((10#$MINUTE))</integer>
  </dict>
  <key>StandardOutPath</key><string>$DATA_DIR/logs/launchd.out.log</string>
  <key>StandardErrorPath</key><string>$DATA_DIR/logs/launchd.err.log</string>
</dict></plist>
EOF2
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load "$PLIST"
    echo "installed: $LABEL — daily at $TIME via $AGENT"
    echo "wrapper: $WRAPPER"
    echo "config.schedule suggestion: {\"provider\": \"launchd\", \"agent\": \"$AGENT\", \"job_id\": \"$LABEL\"}"
    echo "note: 睡眠中错过会在唤醒后补跑一次；关机会错过当次，次日让 Agent「补生成昨天的日报」。"
    ;;
  run-once)
    [[ -f "$CONFIG" ]] || { echo "config not found: $CONFIG (run setup first)" >&2; exit 1; }
    write_wrapper "$AGENT"
    exec /bin/bash "$WRAPPER"
    ;;
  render)
    # write the wrapper without running or scheduling it (inspection / tests)
    write_wrapper "$AGENT"
    echo "$WRAPPER"
    ;;
  uninstall)
    launchctl unload "$PLIST" 2>/dev/null || true
    rm -f "$PLIST"
    echo "uninstalled: $LABEL"
    ;;
  status)
    if [[ -f "$PLIST" ]]; then
      echo "plist: $PLIST"
      launchctl list 2>/dev/null | grep -F "$LABEL" || echo "loaded: no"
      [[ -f "$DATA_DIR/logs/run.log" ]] && { echo "last log lines:"; tail -n 3 "$DATA_DIR/logs/run.log"; }
    else
      echo "not installed"
    fi
    ;;
  *)
    echo "usage: $0 install [--time HH:MM] [--agent claude|codex] | run-once [--agent claude|codex] | render | status | uninstall" >&2
    exit 2
    ;;
esac
